### PR TITLE
:horizontal mode for boxplot

### PR DESCRIPTION
**Pull request by jkrumbiegel**

### CODE REVIEW

**Comment by piever** [comment]
This may be a naive comment, but shouldn't the `orientation = :horizontal` option be done for a general plot? Somehow, I don't feel that it is feasible to do it for each recipe independently.

**Comment by jkrumbiegel** [comment]
I was talking to Simon about the same question today. It seems that for a boxplot, a flip along the identity realized at the transform level would be enough. Simon will try to set something like that up when he has the time. Other plots, especially involving text, might need a bit more specialization. I'll leave this PR up but don't expect it to get merged, I was mostly trying to enable Kevin to do his plot now. This purpose it can still fulfill until there are better solutions.

**Comment by SimonDanisch** [comment]
I guess we should just merge it for now, before I take another month to implement flipping etc :D

**Comment by mkborregaard** [comment]
We've had that question quite a lot on Plots wrt boxplots actually in particular. I think it makes most sense to have it done on the recipe level, so e.g. you can add flipped boxplots over lines or maps or something else. But your general thoughts on this would be useful on https://github.com/JuliaPlots/StatsPlots.jl/pull/289 and https://github.com/JuliaPlots/Plots.jl/pull/2134

**Pull request merged**
