### PR TITLE
Reorganize code

### PR DESCRIPTION
**Pull request by piever**
This is a  round of reorganization / clean up of the GoG functionality.

TODOs:

- [ ] Figure out exact semantics of column / view extraction (even better, make it customizable).

- [x] Figure out best way to combine `Group`, `Data`, and `Style`. So far they can be combined with `*` and in the end they generate a unique `Style` object that contains all the information. Maybe a object with three fields for `Data`, `Group`, and `Style` would be better.

Leaving first thing for vizcon, this PR simply decouples the implementation of that part from the rest.

### CODE REVIEW

**Comment by piever** [comment]
@asinghvi17 what is the simplest way to check that this does not break MakieGallery? I just add MakieGallery on my machine and run test locally?

**Comment by asinghvi17** [comment]
Yeah, that would be the easiest.  I'll hook StatsMakie up with Gitlab later today.

**Comment by asinghvi17** [comment]
you could also shorten the tests:

```julia
record_path = mkpath("recordings")
diff_path      = mkpath("diffs")
MakieGallery.load_database(["statsmakie.jl"]);
MakieGallery.record_examples(record_path)
MakieGallery.run_comparison(record_path, diff_path)
```

**Comment by piever** [comment]
Thanks, that's helpful, tests took a while!

**Pull request merged**
