### PR TITLE
Add general mechanism for dodging and stacking

### PR DESCRIPTION
**Pull request by piever**
This supersedes #12 for groupedbar. The syntax is a bit experimental and I need to see whether it plays nicely with grouping (and with whatever syntax we choose to style multiple things at once like row-vectors in plots), but it's quite nice that there is no code duplication for barplot and boxplot (and violin I imagine when I get around to implementing it). It is based on https://github.com/JuliaPlots/AbstractPlotting.jl/pull/46.

```julia
julia> using Makie, StatsMakie

julia> using StatsMakie: dodge, stack

julia> barplot(stack, 1:4, rand(4,4))

julia> barplot(dodge, 1:4, rand(4,4))

julia> a = repeat(1:5, 20);

julia> b = rand(100, 3);

julia> boxplot(dodge, a, b)
```
screenshot from 2018-11-18 14-34-37

screenshot from 2018-11-18 14-34-50

screenshot from 2018-11-18 14-36-03

As an off topic, I wonder why on my screen the font is so huge whereas Michael's examples in MakieThemes look gorgeous.

### CODE REVIEW

**Comment by Evizero** [comment]
how come the colors in the second one are different?

**Comment by piever** [comment]
Nevermind the colors, palettes in AbstractPlotting still need some adjustments. They currently don't reset for new scenes, so the color depends on when it was in the cycle when I give the plot command.

Concerning the aspect: should the "stack" version also have space between theme?

**Comment by mkborregaard** [comment]
Yes, I think `stack` _and_ `dodge` should have space in between :-)

I'm not sure about the fonts, they seem to always look much nicer on my mac than on my linux box. I do change the style a little in the GGThemr themes though: https://github.com/mkborregaard/MakieThemes.jl/blob/master/src/GGThemr/GGThemr.jl#L19-L38

**Comment by mkborregaard** [comment]
BTW I guess this would also work for histograms, no? 😍

**Comment by piever** [comment]
Yep, stacked barplot definitely looks nicer.

The idea is to get the conversion pipeline to work in the right order so that this would combine nicely with grouping and with statistics, but I still need to think harder about that. One thing that confuses me is the following: in the general groupedbar stacked / dodge case we want to add space between the groups, but do we want to add that space also for histograms? Somehow I don't think we should, but I'm not sure.

**Comment by mkborregaard** [comment]
Definitely no spacing in the case of histograms. On histograms the edges of the bar show the edges between x-axis bins. This is why you by conventional _always_ have a space in bar plots and _never_ have a space in histograms.

**Comment by piever** [comment]
Now I get it, histograms should actually pass on as a computed attribute the width (which should be exactly the difference between edges), whereas the default width of a barplot should be `0.8*minimum(diff(x))`.

**Comment by mkborregaard** [comment]
Yes - we do have uneven-width histograms, check e.g. https://github.com/JuliaPlots/StatPlots.jl#equal-area-histograms

**Pull request merged**
